server:
  port: 8081
database:
  driver: postgres
  host: localhost
  port: 5432
  dbname: mg
  user: jai
  password: jai
env: local
jwt:
  secret: $eEcr3t
  access_token_expire_in: 300
  refresh_token_expire_in: 86400
seed_path: "/Users/jai/Documents/Projects/UK/gin-starter/seeds/"
email:
  host: "smtp.gmail.com"
  port: "587"
  sender: "antonyrajjacobg@gmail.com"
  password: "omui kyoc qvcl eweb"
