server:
  port: 8081
database:
  driver: postgres
  host: localhost
  port: 5432
  dbname: sms
  user: postgres
  password: postgres
env: local
jwt:
  secret: test-code
  access_token_expiration: 3600
  refresh_token_expiration: 86400
  issuer: hangover
seed_path: "/Users/jai/Documents/Projects/UK/gin-starter/seeds/"