server:
  port: 8081
database:
  driver: postgres
  host: localhost
  port: 5432
  dbname: sms_dev
  user: postgres
  password: postgres
env: local
jwt:
  secret: $eEcr3t
  access_token_expire_in: 300
  refresh_token_expire_in: 86400
seed_path: "/home/anto/hangover-sms/seeds/"