package routes

import (
	"time"

	// Import the generated docs
	mw "sms/middlewares"

	// Import the generated docs
	_ "sms/docs" // docs is generated by Swag CLI, you have to import it.

	ginzap "github.com/gin-contrib/zap"
	"github.com/gin-gonic/gin"
	"github.com/robertantonyjaikumar/hangover-common/logger"
	"github.com/robertantonyjaikumar/hangover-common/middlewares"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
	// swagger embed files
)

func NewRouter() *gin.Engine {
	log := logger.GetZapLogger()
	router := gin.New()
	router.Use(middlewares.LogResponseAndRequestBodyMiddleware(log, &ginzap.Config{
		TimeFormat: time.RFC3339,
		UTC:        true,
		SkipPaths:  []string{"/health"},
	}))

	//router.Use(gin.LoggerWithConfig(gin.LoggerConfig{SkipPaths: []string{"/health"}}))
	router.Use(gin.Recovery())
	HealthRoutes(router)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	v1 := router.Group("v1")
	{
		authGroup := v1.Group("auth")
		{
			AuthRoutes(authGroup)
		}
		todoGroup := v1.Group("todo")
		{
			todoGroup.Use(mw.AuthMiddleware())
			TodoRoutes(todoGroup)
		}
		userGroup := v1.Group("user")
		{
			// userGroup.Use(mw.AuthMiddleware())
			UserRoutes(userGroup)
		}

		// crud-generator-router
	}
	return router
}
